model:
  type: classic  # options: classic, lipschitz, randomized
  learning_rate: 0.05 # Learning rate 0.05
  batch_size: 100  # size of the batch
  n_epochs: 2  # Number of epochs to train 40
  noise_percentage: 0.0  # Percentage of noise to add to the data if 0.0 no noise is added

adversarial_training:
  alpha: 0.01  # Alpha value for PGD
  num_iter: 15  # Number of iterations for PGD
  epsilons:  # List of epsilon values to test
    - 0.02
    - 0.04
    - 0.06

attacks:
  - type: normal  # Normal training without attack
  - type: pgd
    attack_class: ProjectedGradientDescent
    alpha: 0.002  # Alpha value for PGD
    num_iter: 10  # Number of iterations for PGD
    epsilons:  # epsilons values for PGD
      - 0.1
      - 0.2
      - 0.4
  - type: pgd_l2
    attack_class: ProjectedGradientDescent_l2
    alpha: 0.005  # A smaller alpha for L2 attacks 0.005
    num_iter: 10
    epsilons:  # epsilons values for PGD  l2
      - 0.1
      - 0.2
      - 0.3
  - type: fgsm
    attack_class: FastGradientSignMethod
    epsilons:  # epsilons values for FGSM
      - 0.02
      - 0.04
      - 0.06
  - type: cw_l2
    attack_class: CarliniWagnerL2
    alpha: 0.01
    num_iter: 20
    epsilons: # epsilons values for CarliniWagnerL2
      - 0.05
      - 0.1
      - 0.2